// Spaces, channels, members, and roles. Capabilities are named strings on a
// role, never permission integers — see docs/architecture.md section 2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: seishin/v1/directory.proto

package seishinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelKind int32

const (
	ChannelKind_CHANNEL_KIND_UNSPECIFIED ChannelKind = 0
	ChannelKind_CHANNEL_KIND_TEXT        ChannelKind = 1
	ChannelKind_CHANNEL_KIND_VOICE       ChannelKind = 2
)

// Enum value maps for ChannelKind.
var (
	ChannelKind_name = map[int32]string{
		0: "CHANNEL_KIND_UNSPECIFIED",
		1: "CHANNEL_KIND_TEXT",
		2: "CHANNEL_KIND_VOICE",
	}
	ChannelKind_value = map[string]int32{
		"CHANNEL_KIND_UNSPECIFIED": 0,
		"CHANNEL_KIND_TEXT":        1,
		"CHANNEL_KIND_VOICE":       2,
	}
)

func (x ChannelKind) Enum() *ChannelKind {
	p := new(ChannelKind)
	*p = x
	return p
}

func (x ChannelKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelKind) Descriptor() protoreflect.EnumDescriptor {
	return file_seishin_v1_directory_proto_enumTypes[0].Descriptor()
}

func (ChannelKind) Type() protoreflect.EnumType {
	return &file_seishin_v1_directory_proto_enumTypes[0]
}

func (x ChannelKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelKind.Descriptor instead.
func (ChannelKind) EnumDescriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{0}
}

// SpatialPolicy governs how clients render pose data on a voice channel.
// See docs/protocol.md section 6.
type SpatialPolicy int32

const (
	SpatialPolicy_SPATIAL_POLICY_UNSPECIFIED SpatialPolicy = 0
	SpatialPolicy_SPATIAL_POLICY_FLAT        SpatialPolicy = 1
	SpatialPolicy_SPATIAL_POLICY_ROOM        SpatialPolicy = 2
	SpatialPolicy_SPATIAL_POLICY_WORLD       SpatialPolicy = 3
)

// Enum value maps for SpatialPolicy.
var (
	SpatialPolicy_name = map[int32]string{
		0: "SPATIAL_POLICY_UNSPECIFIED",
		1: "SPATIAL_POLICY_FLAT",
		2: "SPATIAL_POLICY_ROOM",
		3: "SPATIAL_POLICY_WORLD",
	}
	SpatialPolicy_value = map[string]int32{
		"SPATIAL_POLICY_UNSPECIFIED": 0,
		"SPATIAL_POLICY_FLAT":        1,
		"SPATIAL_POLICY_ROOM":        2,
		"SPATIAL_POLICY_WORLD":       3,
	}
)

func (x SpatialPolicy) Enum() *SpatialPolicy {
	p := new(SpatialPolicy)
	*p = x
	return p
}

func (x SpatialPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpatialPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_seishin_v1_directory_proto_enumTypes[1].Descriptor()
}

func (SpatialPolicy) Type() protoreflect.EnumType {
	return &file_seishin_v1_directory_proto_enumTypes[1]
}

func (x SpatialPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpatialPolicy.Descriptor instead.
func (SpatialPolicy) EnumDescriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{1}
}

type Space struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_seishin_v1_directory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{0}
}

func (x *Space) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Channel struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SpaceId   string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Kind      ChannelKind            `protobuf:"varint,4,opt,name=kind,proto3,enum=seishin.v1.ChannelKind" json:"kind,omitempty"`
	// Meaningful only when kind == CHANNEL_KIND_VOICE.
	SpatialPolicy SpatialPolicy `protobuf:"varint,5,opt,name=spatial_policy,json=spatialPolicy,proto3,enum=seishin.v1.SpatialPolicy" json:"spatial_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_seishin_v1_directory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Channel) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetKind() ChannelKind {
	if x != nil {
		return x.Kind
	}
	return ChannelKind_CHANNEL_KIND_UNSPECIFIED
}

func (x *Channel) GetSpatialPolicy() SpatialPolicy {
	if x != nil {
		return x.SpatialPolicy
	}
	return SpatialPolicy_SPATIAL_POLICY_UNSPECIFIED
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_seishin_v1_directory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type Role struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoleId string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Named capability strings, e.g. "channel.create". Never a permission
	// integer.
	Capabilities  []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_seishin_v1_directory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{3}
}

func (x *Role) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ListSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesRequest) Reset() {
	*x = ListSpacesRequest{}
	mi := &file_seishin_v1_directory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesRequest) ProtoMessage() {}

func (x *ListSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesRequest.ProtoReflect.Descriptor instead.
func (*ListSpacesRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{4}
}

type ListSpacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaces        []*Space               `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesResponse) Reset() {
	*x = ListSpacesResponse{}
	mi := &file_seishin_v1_directory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesResponse) ProtoMessage() {}

func (x *ListSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesResponse.ProtoReflect.Descriptor instead.
func (*ListSpacesResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{5}
}

func (x *ListSpacesResponse) GetSpaces() []*Space {
	if x != nil {
		return x.Spaces
	}
	return nil
}

type GetSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpaceRequest) Reset() {
	*x = GetSpaceRequest{}
	mi := &file_seishin_v1_directory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceRequest) ProtoMessage() {}

func (x *GetSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceRequest.ProtoReflect.Descriptor instead.
func (*GetSpaceRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{6}
}

func (x *GetSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type GetSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Space         *Space                 `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpaceResponse) Reset() {
	*x = GetSpaceResponse{}
	mi := &file_seishin_v1_directory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceResponse) ProtoMessage() {}

func (x *GetSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceResponse.ProtoReflect.Descriptor instead.
func (*GetSpaceResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{7}
}

func (x *GetSpaceResponse) GetSpace() *Space {
	if x != nil {
		return x.Space
	}
	return nil
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_seishin_v1_directory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{8}
}

func (x *ListChannelsRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_seishin_v1_directory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{9}
}

func (x *ListChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          ChannelKind            `protobuf:"varint,3,opt,name=kind,proto3,enum=seishin.v1.ChannelKind" json:"kind,omitempty"`
	SpatialPolicy SpatialPolicy          `protobuf:"varint,4,opt,name=spatial_policy,json=spatialPolicy,proto3,enum=seishin.v1.SpatialPolicy" json:"spatial_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_seishin_v1_directory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{10}
}

func (x *CreateChannelRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelRequest) GetKind() ChannelKind {
	if x != nil {
		return x.Kind
	}
	return ChannelKind_CHANNEL_KIND_UNSPECIFIED
}

func (x *CreateChannelRequest) GetSpatialPolicy() SpatialPolicy {
	if x != nil {
		return x.SpatialPolicy
	}
	return SpatialPolicy_SPATIAL_POLICY_UNSPECIFIED
}

type CreateChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelResponse) Reset() {
	*x = CreateChannelResponse{}
	mi := &file_seishin_v1_directory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResponse) ProtoMessage() {}

func (x *CreateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{11}
}

func (x *CreateChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_seishin_v1_directory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{12}
}

func (x *ListMembersRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_seishin_v1_directory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{13}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_seishin_v1_directory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{14}
}

func (x *ListRolesRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_seishin_v1_directory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_directory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_directory_proto_rawDescGZIP(), []int{15}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_seishin_v1_directory_proto protoreflect.FileDescriptor

const file_seishin_v1_directory_proto_rawDesc = "" +
	"\n" +
	"\x1aseishin/v1/directory.proto\x12\n" +
	"seishin.v1\"6\n" +
	"\x05Space\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc6\x01\n" +
	"\aChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x17.seishin.v1.ChannelKindR\x04kind\x12@\n" +
	"\x0espatial_policy\x18\x05 \x01(\x0e2\x19.seishin.v1.SpatialPolicyR\rspatialPolicy\"<\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\"W\n" +
	"\x04Role\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x13\n" +
	"\x11ListSpacesRequest\"?\n" +
	"\x12ListSpacesResponse\x12)\n" +
	"\x06spaces\x18\x01 \x03(\v2\x11.seishin.v1.SpaceR\x06spaces\",\n" +
	"\x0fGetSpaceRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\";\n" +
	"\x10GetSpaceResponse\x12'\n" +
	"\x05space\x18\x01 \x01(\v2\x11.seishin.v1.SpaceR\x05space\"0\n" +
	"\x13ListChannelsRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"G\n" +
	"\x14ListChannelsResponse\x12/\n" +
	"\bchannels\x18\x01 \x03(\v2\x13.seishin.v1.ChannelR\bchannels\"\xb4\x01\n" +
	"\x14CreateChannelRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x17.seishin.v1.ChannelKindR\x04kind\x12@\n" +
	"\x0espatial_policy\x18\x04 \x01(\x0e2\x19.seishin.v1.SpatialPolicyR\rspatialPolicy\"F\n" +
	"\x15CreateChannelResponse\x12-\n" +
	"\achannel\x18\x01 \x01(\v2\x13.seishin.v1.ChannelR\achannel\"/\n" +
	"\x12ListMembersRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"C\n" +
	"\x13ListMembersResponse\x12,\n" +
	"\amembers\x18\x01 \x03(\v2\x12.seishin.v1.MemberR\amembers\"-\n" +
	"\x10ListRolesRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\";\n" +
	"\x11ListRolesResponse\x12&\n" +
	"\x05roles\x18\x01 \x03(\v2\x10.seishin.v1.RoleR\x05roles*Z\n" +
	"\vChannelKind\x12\x1c\n" +
	"\x18CHANNEL_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHANNEL_KIND_TEXT\x10\x01\x12\x16\n" +
	"\x12CHANNEL_KIND_VOICE\x10\x02*{\n" +
	"\rSpatialPolicy\x12\x1e\n" +
	"\x1aSPATIAL_POLICY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SPATIAL_POLICY_FLAT\x10\x01\x12\x17\n" +
	"\x13SPATIAL_POLICY_ROOM\x10\x02\x12\x18\n" +
	"\x14SPATIAL_POLICY_WORLD\x10\x032\xe9\x03\n" +
	"\x10DirectoryService\x12K\n" +
	"\n" +
	"ListSpaces\x12\x1d.seishin.v1.ListSpacesRequest\x1a\x1e.seishin.v1.ListSpacesResponse\x12E\n" +
	"\bGetSpace\x12\x1b.seishin.v1.GetSpaceRequest\x1a\x1c.seishin.v1.GetSpaceResponse\x12Q\n" +
	"\fListChannels\x12\x1f.seishin.v1.ListChannelsRequest\x1a .seishin.v1.ListChannelsResponse\x12T\n" +
	"\rCreateChannel\x12 .seishin.v1.CreateChannelRequest\x1a!.seishin.v1.CreateChannelResponse\x12N\n" +
	"\vListMembers\x12\x1e.seishin.v1.ListMembersRequest\x1a\x1f.seishin.v1.ListMembersResponse\x12H\n" +
	"\tListRoles\x12\x1c.seishin.v1.ListRolesRequest\x1a\x1d.seishin.v1.ListRolesResponseB>Z<github.com/seishinapp/seishin/api/proto/seishin/v1;seishinv1b\x06proto3"

var (
	file_seishin_v1_directory_proto_rawDescOnce sync.Once
	file_seishin_v1_directory_proto_rawDescData []byte
)

func file_seishin_v1_directory_proto_rawDescGZIP() []byte {
	file_seishin_v1_directory_proto_rawDescOnce.Do(func() {
		file_seishin_v1_directory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seishin_v1_directory_proto_rawDesc), len(file_seishin_v1_directory_proto_rawDesc)))
	})
	return file_seishin_v1_directory_proto_rawDescData
}

var file_seishin_v1_directory_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_seishin_v1_directory_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_seishin_v1_directory_proto_goTypes = []any{
	(ChannelKind)(0),              // 0: seishin.v1.ChannelKind
	(SpatialPolicy)(0),            // 1: seishin.v1.SpatialPolicy
	(*Space)(nil),                 // 2: seishin.v1.Space
	(*Channel)(nil),               // 3: seishin.v1.Channel
	(*Member)(nil),                // 4: seishin.v1.Member
	(*Role)(nil),                  // 5: seishin.v1.Role
	(*ListSpacesRequest)(nil),     // 6: seishin.v1.ListSpacesRequest
	(*ListSpacesResponse)(nil),    // 7: seishin.v1.ListSpacesResponse
	(*GetSpaceRequest)(nil),       // 8: seishin.v1.GetSpaceRequest
	(*GetSpaceResponse)(nil),      // 9: seishin.v1.GetSpaceResponse
	(*ListChannelsRequest)(nil),   // 10: seishin.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),  // 11: seishin.v1.ListChannelsResponse
	(*CreateChannelRequest)(nil),  // 12: seishin.v1.CreateChannelRequest
	(*CreateChannelResponse)(nil), // 13: seishin.v1.CreateChannelResponse
	(*ListMembersRequest)(nil),    // 14: seishin.v1.ListMembersRequest
	(*ListMembersResponse)(nil),   // 15: seishin.v1.ListMembersResponse
	(*ListRolesRequest)(nil),      // 16: seishin.v1.ListRolesRequest
	(*ListRolesResponse)(nil),     // 17: seishin.v1.ListRolesResponse
}
var file_seishin_v1_directory_proto_depIdxs = []int32{
	0,  // 0: seishin.v1.Channel.kind:type_name -> seishin.v1.ChannelKind
	1,  // 1: seishin.v1.Channel.spatial_policy:type_name -> seishin.v1.SpatialPolicy
	2,  // 2: seishin.v1.ListSpacesResponse.spaces:type_name -> seishin.v1.Space
	2,  // 3: seishin.v1.GetSpaceResponse.space:type_name -> seishin.v1.Space
	3,  // 4: seishin.v1.ListChannelsResponse.channels:type_name -> seishin.v1.Channel
	0,  // 5: seishin.v1.CreateChannelRequest.kind:type_name -> seishin.v1.ChannelKind
	1,  // 6: seishin.v1.CreateChannelRequest.spatial_policy:type_name -> seishin.v1.SpatialPolicy
	3,  // 7: seishin.v1.CreateChannelResponse.channel:type_name -> seishin.v1.Channel
	4,  // 8: seishin.v1.ListMembersResponse.members:type_name -> seishin.v1.Member
	5,  // 9: seishin.v1.ListRolesResponse.roles:type_name -> seishin.v1.Role
	6,  // 10: seishin.v1.DirectoryService.ListSpaces:input_type -> seishin.v1.ListSpacesRequest
	8,  // 11: seishin.v1.DirectoryService.GetSpace:input_type -> seishin.v1.GetSpaceRequest
	10, // 12: seishin.v1.DirectoryService.ListChannels:input_type -> seishin.v1.ListChannelsRequest
	12, // 13: seishin.v1.DirectoryService.CreateChannel:input_type -> seishin.v1.CreateChannelRequest
	14, // 14: seishin.v1.DirectoryService.ListMembers:input_type -> seishin.v1.ListMembersRequest
	16, // 15: seishin.v1.DirectoryService.ListRoles:input_type -> seishin.v1.ListRolesRequest
	7,  // 16: seishin.v1.DirectoryService.ListSpaces:output_type -> seishin.v1.ListSpacesResponse
	9,  // 17: seishin.v1.DirectoryService.GetSpace:output_type -> seishin.v1.GetSpaceResponse
	11, // 18: seishin.v1.DirectoryService.ListChannels:output_type -> seishin.v1.ListChannelsResponse
	13, // 19: seishin.v1.DirectoryService.CreateChannel:output_type -> seishin.v1.CreateChannelResponse
	15, // 20: seishin.v1.DirectoryService.ListMembers:output_type -> seishin.v1.ListMembersResponse
	17, // 21: seishin.v1.DirectoryService.ListRoles:output_type -> seishin.v1.ListRolesResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_seishin_v1_directory_proto_init() }
func file_seishin_v1_directory_proto_init() {
	if File_seishin_v1_directory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seishin_v1_directory_proto_rawDesc), len(file_seishin_v1_directory_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seishin_v1_directory_proto_goTypes,
		DependencyIndexes: file_seishin_v1_directory_proto_depIdxs,
		EnumInfos:         file_seishin_v1_directory_proto_enumTypes,
		MessageInfos:      file_seishin_v1_directory_proto_msgTypes,
	}.Build()
	File_seishin_v1_directory_proto = out.File
	file_seishin_v1_directory_proto_goTypes = nil
	file_seishin_v1_directory_proto_depIdxs = nil
}
