// Ephemeral presence: held in NATS JetStream KV + memory, never Postgres.
// A server restart is expected to reset presence with no correctness impact
// beyond a brief gap. See docs/architecture.md section 5.2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: seishin/v1/presence.proto

package seishinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceStatus int32

const (
	PresenceStatus_PRESENCE_STATUS_UNSPECIFIED PresenceStatus = 0
	PresenceStatus_PRESENCE_STATUS_ONLINE      PresenceStatus = 1
	PresenceStatus_PRESENCE_STATUS_AWAY        PresenceStatus = 2
	PresenceStatus_PRESENCE_STATUS_OFFLINE     PresenceStatus = 3
)

// Enum value maps for PresenceStatus.
var (
	PresenceStatus_name = map[int32]string{
		0: "PRESENCE_STATUS_UNSPECIFIED",
		1: "PRESENCE_STATUS_ONLINE",
		2: "PRESENCE_STATUS_AWAY",
		3: "PRESENCE_STATUS_OFFLINE",
	}
	PresenceStatus_value = map[string]int32{
		"PRESENCE_STATUS_UNSPECIFIED": 0,
		"PRESENCE_STATUS_ONLINE":      1,
		"PRESENCE_STATUS_AWAY":        2,
		"PRESENCE_STATUS_OFFLINE":     3,
	}
)

func (x PresenceStatus) Enum() *PresenceStatus {
	p := new(PresenceStatus)
	*p = x
	return p
}

func (x PresenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_seishin_v1_presence_proto_enumTypes[0].Descriptor()
}

func (PresenceStatus) Type() protoreflect.EnumType {
	return &file_seishin_v1_presence_proto_enumTypes[0]
}

func (x PresenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceStatus.Descriptor instead.
func (PresenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_seishin_v1_presence_proto_rawDescGZIP(), []int{0}
}

type PresenceState struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status PresenceStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=seishin.v1.PresenceStatus" json:"status,omitempty"`
	// Voice channel_id the user is currently connected to, empty if none.
	ChannelId     string `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceState) Reset() {
	*x = PresenceState{}
	mi := &file_seishin_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceState) ProtoMessage() {}

func (x *PresenceState) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceState.ProtoReflect.Descriptor instead.
func (*PresenceState) Descriptor() ([]byte, []int) {
	return file_seishin_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *PresenceState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceState) GetStatus() PresenceStatus {
	if x != nil {
		return x.Status
	}
	return PresenceStatus_PRESENCE_STATUS_UNSPECIFIED
}

func (x *PresenceState) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type SetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PresenceStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=seishin.v1.PresenceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPresenceRequest) Reset() {
	*x = SetPresenceRequest{}
	mi := &file_seishin_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPresenceRequest) ProtoMessage() {}

func (x *SetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPresenceRequest.ProtoReflect.Descriptor instead.
func (*SetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_presence_proto_rawDescGZIP(), []int{1}
}

func (x *SetPresenceRequest) GetStatus() PresenceStatus {
	if x != nil {
		return x.Status
	}
	return PresenceStatus_PRESENCE_STATUS_UNSPECIFIED
}

type SetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPresenceResponse) Reset() {
	*x = SetPresenceResponse{}
	mi := &file_seishin_v1_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPresenceResponse) ProtoMessage() {}

func (x *SetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPresenceResponse.ProtoReflect.Descriptor instead.
func (*SetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_presence_proto_rawDescGZIP(), []int{2}
}

type ListPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresenceRequest) Reset() {
	*x = ListPresenceRequest{}
	mi := &file_seishin_v1_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresenceRequest) ProtoMessage() {}

func (x *ListPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresenceRequest.ProtoReflect.Descriptor instead.
func (*ListPresenceRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_presence_proto_rawDescGZIP(), []int{3}
}

func (x *ListPresenceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type ListPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      []*PresenceState       `protobuf:"bytes,1,rep,name=presence,proto3" json:"presence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresenceResponse) Reset() {
	*x = ListPresenceResponse{}
	mi := &file_seishin_v1_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresenceResponse) ProtoMessage() {}

func (x *ListPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresenceResponse.ProtoReflect.Descriptor instead.
func (*ListPresenceResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_presence_proto_rawDescGZIP(), []int{4}
}

func (x *ListPresenceResponse) GetPresence() []*PresenceState {
	if x != nil {
		return x.Presence
	}
	return nil
}

var File_seishin_v1_presence_proto protoreflect.FileDescriptor

const file_seishin_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x19seishin/v1/presence.proto\x12\n" +
	"seishin.v1\"{\n" +
	"\rPresenceState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.seishin.v1.PresenceStatusR\x06status\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\"H\n" +
	"\x12SetPresenceRequest\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.seishin.v1.PresenceStatusR\x06status\"\x15\n" +
	"\x13SetPresenceResponse\"0\n" +
	"\x13ListPresenceRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"M\n" +
	"\x14ListPresenceResponse\x125\n" +
	"\bpresence\x18\x01 \x03(\v2\x19.seishin.v1.PresenceStateR\bpresence*\x84\x01\n" +
	"\x0ePresenceStatus\x12\x1f\n" +
	"\x1bPRESENCE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PRESENCE_STATUS_ONLINE\x10\x01\x12\x18\n" +
	"\x14PRESENCE_STATUS_AWAY\x10\x02\x12\x1b\n" +
	"\x17PRESENCE_STATUS_OFFLINE\x10\x032\xb4\x01\n" +
	"\x0fPresenceService\x12N\n" +
	"\vSetPresence\x12\x1e.seishin.v1.SetPresenceRequest\x1a\x1f.seishin.v1.SetPresenceResponse\x12Q\n" +
	"\fListPresence\x12\x1f.seishin.v1.ListPresenceRequest\x1a .seishin.v1.ListPresenceResponseB>Z<github.com/seishinapp/seishin/api/proto/seishin/v1;seishinv1b\x06proto3"

var (
	file_seishin_v1_presence_proto_rawDescOnce sync.Once
	file_seishin_v1_presence_proto_rawDescData []byte
)

func file_seishin_v1_presence_proto_rawDescGZIP() []byte {
	file_seishin_v1_presence_proto_rawDescOnce.Do(func() {
		file_seishin_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seishin_v1_presence_proto_rawDesc), len(file_seishin_v1_presence_proto_rawDesc)))
	})
	return file_seishin_v1_presence_proto_rawDescData
}

var file_seishin_v1_presence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_seishin_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_seishin_v1_presence_proto_goTypes = []any{
	(PresenceStatus)(0),          // 0: seishin.v1.PresenceStatus
	(*PresenceState)(nil),        // 1: seishin.v1.PresenceState
	(*SetPresenceRequest)(nil),   // 2: seishin.v1.SetPresenceRequest
	(*SetPresenceResponse)(nil),  // 3: seishin.v1.SetPresenceResponse
	(*ListPresenceRequest)(nil),  // 4: seishin.v1.ListPresenceRequest
	(*ListPresenceResponse)(nil), // 5: seishin.v1.ListPresenceResponse
}
var file_seishin_v1_presence_proto_depIdxs = []int32{
	0, // 0: seishin.v1.PresenceState.status:type_name -> seishin.v1.PresenceStatus
	0, // 1: seishin.v1.SetPresenceRequest.status:type_name -> seishin.v1.PresenceStatus
	1, // 2: seishin.v1.ListPresenceResponse.presence:type_name -> seishin.v1.PresenceState
	2, // 3: seishin.v1.PresenceService.SetPresence:input_type -> seishin.v1.SetPresenceRequest
	4, // 4: seishin.v1.PresenceService.ListPresence:input_type -> seishin.v1.ListPresenceRequest
	3, // 5: seishin.v1.PresenceService.SetPresence:output_type -> seishin.v1.SetPresenceResponse
	5, // 6: seishin.v1.PresenceService.ListPresence:output_type -> seishin.v1.ListPresenceResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_seishin_v1_presence_proto_init() }
func file_seishin_v1_presence_proto_init() {
	if File_seishin_v1_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seishin_v1_presence_proto_rawDesc), len(file_seishin_v1_presence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seishin_v1_presence_proto_goTypes,
		DependencyIndexes: file_seishin_v1_presence_proto_depIdxs,
		EnumInfos:         file_seishin_v1_presence_proto_enumTypes,
		MessageInfos:      file_seishin_v1_presence_proto_msgTypes,
	}.Build()
	File_seishin_v1_presence_proto = out.File
	file_seishin_v1_presence_proto_goTypes = nil
	file_seishin_v1_presence_proto_depIdxs = nil
}
