// Identity and session establishment: the handshake described in
// docs/protocol.md section 3, expressed as Canonical Platform API messages.
// The native protocol adds framing on top of these same messages; it defines
// no session semantics of its own.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: seishin/v1/session.proto

package seishinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identity is derived from an Ed25519 public key, never issued by a server.
// See docs/architecture.md section 6.
type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ed25519 public key, 32 bytes. The root of identity.
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Canonical user ID, deterministically derived from public_key.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// "@user:home.example", set only when a home provider issued a token
	// during authentication. Empty for guests and keys with no home provider.
	Handle        string `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_seishin_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Identity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Identity) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_seishin_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *ClientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Motd          string                 `protobuf:"bytes,2,opt,name=motd,proto3" json:"motd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_seishin_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetMotd() string {
	if x != nil {
		return x.Motd
	}
	return ""
}

type HelloRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ClientInfo      *ClientInfo            `protobuf:"bytes,2,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_seishin_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *HelloRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HelloRequest) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerInfo    *ServerInfo            `protobuf:"bytes,2,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	// Server-generated nonce; the Authenticate signature must cover it.
	Nonce         []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AuthMethods   []string `protobuf:"bytes,4,rep,name=auth_methods,json=authMethods,proto3" json:"auth_methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_seishin_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *HelloResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HelloResponse) GetServerInfo() *ServerInfo {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

func (x *HelloResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *HelloResponse) GetAuthMethods() []string {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

type AuthenticateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdentityPublicKey []byte                 `protobuf:"bytes,1,opt,name=identity_public_key,json=identityPublicKey,proto3" json:"identity_public_key,omitempty"`
	// The nonce returned by Hello. The server rejects an unknown or
	// already-consumed nonce.
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Signature over nonce, proving possession of the private key. Over the
	// native CXP/1 transport this additionally covers the transport transcript
	// hash, binding the proof to one connection — see docs/protocol.md
	// section 3. This HTTP surface has no equivalent transcript to bind to.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// Optional OIDC token from a home provider. Omitted for guests and for
	// keys with no home provider.
	HomeProviderToken string `protobuf:"bytes,4,opt,name=home_provider_token,json=homeProviderToken,proto3" json:"home_provider_token,omitempty"`
	// Required when identity_public_key is a freshly generated guest key.
	GuestDisplayName string `protobuf:"bytes,5,opt,name=guest_display_name,json=guestDisplayName,proto3" json:"guest_display_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_seishin_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticateRequest) GetIdentityPublicKey() []byte {
	if x != nil {
		return x.IdentityPublicKey
	}
	return nil
}

func (x *AuthenticateRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AuthenticateRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthenticateRequest) GetHomeProviderToken() string {
	if x != nil {
		return x.HomeProviderToken
	}
	return ""
}

func (x *AuthenticateRequest) GetGuestDisplayName() string {
	if x != nil {
		return x.GuestDisplayName
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_seishin_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *AuthenticateResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type Session struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Identity  *Identity              `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// Named capability strings computed from the identity's roles at connect
	// time. Never permission integers. See docs/architecture.md section 2.
	Capabilities []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Opaque token for Resume. Valid for 60s after disconnect, per
	// docs/protocol.md section 8.
	ResumeToken   string `protobuf:"bytes,4,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_seishin_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Session) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Session) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ResumeToken   string                 `protobuf:"bytes,2,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_seishin_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *ResumeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResumeRequest) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_seishin_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seishin_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_seishin_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_seishin_v1_session_proto protoreflect.FileDescriptor

const file_seishin_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x18seishin/v1/session.proto\x12\n" +
	"seishin.v1\"Z\n" +
	"\bIdentity\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06handle\x18\x03 \x01(\tR\x06handle\"V\n" +
	"\n" +
	"ClientInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"4\n" +
	"\n" +
	"ServerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04motd\x18\x02 \x01(\tR\x04motd\"r\n" +
	"\fHelloRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\vclient_info\x18\x02 \x01(\v2\x16.seishin.v1.ClientInfoR\n" +
	"clientInfo\"\xa8\x01\n" +
	"\rHelloResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x127\n" +
	"\vserver_info\x18\x02 \x01(\v2\x16.seishin.v1.ServerInfoR\n" +
	"serverInfo\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12!\n" +
	"\fauth_methods\x18\x04 \x03(\tR\vauthMethods\"\xd7\x01\n" +
	"\x13AuthenticateRequest\x12.\n" +
	"\x13identity_public_key\x18\x01 \x01(\fR\x11identityPublicKey\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12.\n" +
	"\x13home_provider_token\x18\x04 \x01(\tR\x11homeProviderToken\x12,\n" +
	"\x12guest_display_name\x18\x05 \x01(\tR\x10guestDisplayName\"E\n" +
	"\x14AuthenticateResponse\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.seishin.v1.SessionR\asession\"\xa1\x01\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\bidentity\x18\x02 \x01(\v2\x14.seishin.v1.IdentityR\bidentity\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12!\n" +
	"\fresume_token\x18\x04 \x01(\tR\vresumeToken\"Q\n" +
	"\rResumeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fresume_token\x18\x02 \x01(\tR\vresumeToken\"?\n" +
	"\x0eResumeResponse\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.seishin.v1.SessionR\asession2\xe2\x01\n" +
	"\x0eSessionService\x12<\n" +
	"\x05Hello\x12\x18.seishin.v1.HelloRequest\x1a\x19.seishin.v1.HelloResponse\x12Q\n" +
	"\fAuthenticate\x12\x1f.seishin.v1.AuthenticateRequest\x1a .seishin.v1.AuthenticateResponse\x12?\n" +
	"\x06Resume\x12\x19.seishin.v1.ResumeRequest\x1a\x1a.seishin.v1.ResumeResponseB>Z<github.com/seishinapp/seishin/api/proto/seishin/v1;seishinv1b\x06proto3"

var (
	file_seishin_v1_session_proto_rawDescOnce sync.Once
	file_seishin_v1_session_proto_rawDescData []byte
)

func file_seishin_v1_session_proto_rawDescGZIP() []byte {
	file_seishin_v1_session_proto_rawDescOnce.Do(func() {
		file_seishin_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seishin_v1_session_proto_rawDesc), len(file_seishin_v1_session_proto_rawDesc)))
	})
	return file_seishin_v1_session_proto_rawDescData
}

var file_seishin_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_seishin_v1_session_proto_goTypes = []any{
	(*Identity)(nil),             // 0: seishin.v1.Identity
	(*ClientInfo)(nil),           // 1: seishin.v1.ClientInfo
	(*ServerInfo)(nil),           // 2: seishin.v1.ServerInfo
	(*HelloRequest)(nil),         // 3: seishin.v1.HelloRequest
	(*HelloResponse)(nil),        // 4: seishin.v1.HelloResponse
	(*AuthenticateRequest)(nil),  // 5: seishin.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 6: seishin.v1.AuthenticateResponse
	(*Session)(nil),              // 7: seishin.v1.Session
	(*ResumeRequest)(nil),        // 8: seishin.v1.ResumeRequest
	(*ResumeResponse)(nil),       // 9: seishin.v1.ResumeResponse
}
var file_seishin_v1_session_proto_depIdxs = []int32{
	1, // 0: seishin.v1.HelloRequest.client_info:type_name -> seishin.v1.ClientInfo
	2, // 1: seishin.v1.HelloResponse.server_info:type_name -> seishin.v1.ServerInfo
	7, // 2: seishin.v1.AuthenticateResponse.session:type_name -> seishin.v1.Session
	0, // 3: seishin.v1.Session.identity:type_name -> seishin.v1.Identity
	7, // 4: seishin.v1.ResumeResponse.session:type_name -> seishin.v1.Session
	3, // 5: seishin.v1.SessionService.Hello:input_type -> seishin.v1.HelloRequest
	5, // 6: seishin.v1.SessionService.Authenticate:input_type -> seishin.v1.AuthenticateRequest
	8, // 7: seishin.v1.SessionService.Resume:input_type -> seishin.v1.ResumeRequest
	4, // 8: seishin.v1.SessionService.Hello:output_type -> seishin.v1.HelloResponse
	6, // 9: seishin.v1.SessionService.Authenticate:output_type -> seishin.v1.AuthenticateResponse
	9, // 10: seishin.v1.SessionService.Resume:output_type -> seishin.v1.ResumeResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_seishin_v1_session_proto_init() }
func file_seishin_v1_session_proto_init() {
	if File_seishin_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seishin_v1_session_proto_rawDesc), len(file_seishin_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seishin_v1_session_proto_goTypes,
		DependencyIndexes: file_seishin_v1_session_proto_depIdxs,
		MessageInfos:      file_seishin_v1_session_proto_msgTypes,
	}.Build()
	File_seishin_v1_session_proto = out.File
	file_seishin_v1_session_proto_goTypes = nil
	file_seishin_v1_session_proto_depIdxs = nil
}
