// Spaces, channels, members, and roles. Capabilities are named strings on a
// role, never permission integers — see docs/architecture.md section 2.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: seishin/v1/directory.proto

package seishinv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/seishinapp/seishin/api/proto/seishin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DirectoryServiceName is the fully-qualified name of the DirectoryService service.
	DirectoryServiceName = "seishin.v1.DirectoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DirectoryServiceListSpacesProcedure is the fully-qualified name of the DirectoryService's
	// ListSpaces RPC.
	DirectoryServiceListSpacesProcedure = "/seishin.v1.DirectoryService/ListSpaces"
	// DirectoryServiceGetSpaceProcedure is the fully-qualified name of the DirectoryService's GetSpace
	// RPC.
	DirectoryServiceGetSpaceProcedure = "/seishin.v1.DirectoryService/GetSpace"
	// DirectoryServiceListChannelsProcedure is the fully-qualified name of the DirectoryService's
	// ListChannels RPC.
	DirectoryServiceListChannelsProcedure = "/seishin.v1.DirectoryService/ListChannels"
	// DirectoryServiceCreateChannelProcedure is the fully-qualified name of the DirectoryService's
	// CreateChannel RPC.
	DirectoryServiceCreateChannelProcedure = "/seishin.v1.DirectoryService/CreateChannel"
	// DirectoryServiceListMembersProcedure is the fully-qualified name of the DirectoryService's
	// ListMembers RPC.
	DirectoryServiceListMembersProcedure = "/seishin.v1.DirectoryService/ListMembers"
	// DirectoryServiceListRolesProcedure is the fully-qualified name of the DirectoryService's
	// ListRoles RPC.
	DirectoryServiceListRolesProcedure = "/seishin.v1.DirectoryService/ListRoles"
)

// DirectoryServiceClient is a client for the seishin.v1.DirectoryService service.
type DirectoryServiceClient interface {
	ListSpaces(context.Context, *connect.Request[v1.ListSpacesRequest]) (*connect.Response[v1.ListSpacesResponse], error)
	GetSpace(context.Context, *connect.Request[v1.GetSpaceRequest]) (*connect.Response[v1.GetSpaceResponse], error)
	ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error)
	CreateChannel(context.Context, *connect.Request[v1.CreateChannelRequest]) (*connect.Response[v1.CreateChannelResponse], error)
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
}

// NewDirectoryServiceClient constructs a client for the seishin.v1.DirectoryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDirectoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DirectoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	directoryServiceMethods := v1.File_seishin_v1_directory_proto.Services().ByName("DirectoryService").Methods()
	return &directoryServiceClient{
		listSpaces: connect.NewClient[v1.ListSpacesRequest, v1.ListSpacesResponse](
			httpClient,
			baseURL+DirectoryServiceListSpacesProcedure,
			connect.WithSchema(directoryServiceMethods.ByName("ListSpaces")),
			connect.WithClientOptions(opts...),
		),
		getSpace: connect.NewClient[v1.GetSpaceRequest, v1.GetSpaceResponse](
			httpClient,
			baseURL+DirectoryServiceGetSpaceProcedure,
			connect.WithSchema(directoryServiceMethods.ByName("GetSpace")),
			connect.WithClientOptions(opts...),
		),
		listChannels: connect.NewClient[v1.ListChannelsRequest, v1.ListChannelsResponse](
			httpClient,
			baseURL+DirectoryServiceListChannelsProcedure,
			connect.WithSchema(directoryServiceMethods.ByName("ListChannels")),
			connect.WithClientOptions(opts...),
		),
		createChannel: connect.NewClient[v1.CreateChannelRequest, v1.CreateChannelResponse](
			httpClient,
			baseURL+DirectoryServiceCreateChannelProcedure,
			connect.WithSchema(directoryServiceMethods.ByName("CreateChannel")),
			connect.WithClientOptions(opts...),
		),
		listMembers: connect.NewClient[v1.ListMembersRequest, v1.ListMembersResponse](
			httpClient,
			baseURL+DirectoryServiceListMembersProcedure,
			connect.WithSchema(directoryServiceMethods.ByName("ListMembers")),
			connect.WithClientOptions(opts...),
		),
		listRoles: connect.NewClient[v1.ListRolesRequest, v1.ListRolesResponse](
			httpClient,
			baseURL+DirectoryServiceListRolesProcedure,
			connect.WithSchema(directoryServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// directoryServiceClient implements DirectoryServiceClient.
type directoryServiceClient struct {
	listSpaces    *connect.Client[v1.ListSpacesRequest, v1.ListSpacesResponse]
	getSpace      *connect.Client[v1.GetSpaceRequest, v1.GetSpaceResponse]
	listChannels  *connect.Client[v1.ListChannelsRequest, v1.ListChannelsResponse]
	createChannel *connect.Client[v1.CreateChannelRequest, v1.CreateChannelResponse]
	listMembers   *connect.Client[v1.ListMembersRequest, v1.ListMembersResponse]
	listRoles     *connect.Client[v1.ListRolesRequest, v1.ListRolesResponse]
}

// ListSpaces calls seishin.v1.DirectoryService.ListSpaces.
func (c *directoryServiceClient) ListSpaces(ctx context.Context, req *connect.Request[v1.ListSpacesRequest]) (*connect.Response[v1.ListSpacesResponse], error) {
	return c.listSpaces.CallUnary(ctx, req)
}

// GetSpace calls seishin.v1.DirectoryService.GetSpace.
func (c *directoryServiceClient) GetSpace(ctx context.Context, req *connect.Request[v1.GetSpaceRequest]) (*connect.Response[v1.GetSpaceResponse], error) {
	return c.getSpace.CallUnary(ctx, req)
}

// ListChannels calls seishin.v1.DirectoryService.ListChannels.
func (c *directoryServiceClient) ListChannels(ctx context.Context, req *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error) {
	return c.listChannels.CallUnary(ctx, req)
}

// CreateChannel calls seishin.v1.DirectoryService.CreateChannel.
func (c *directoryServiceClient) CreateChannel(ctx context.Context, req *connect.Request[v1.CreateChannelRequest]) (*connect.Response[v1.CreateChannelResponse], error) {
	return c.createChannel.CallUnary(ctx, req)
}

// ListMembers calls seishin.v1.DirectoryService.ListMembers.
func (c *directoryServiceClient) ListMembers(ctx context.Context, req *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// ListRoles calls seishin.v1.DirectoryService.ListRoles.
func (c *directoryServiceClient) ListRoles(ctx context.Context, req *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// DirectoryServiceHandler is an implementation of the seishin.v1.DirectoryService service.
type DirectoryServiceHandler interface {
	ListSpaces(context.Context, *connect.Request[v1.ListSpacesRequest]) (*connect.Response[v1.ListSpacesResponse], error)
	GetSpace(context.Context, *connect.Request[v1.GetSpaceRequest]) (*connect.Response[v1.GetSpaceResponse], error)
	ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error)
	CreateChannel(context.Context, *connect.Request[v1.CreateChannelRequest]) (*connect.Response[v1.CreateChannelResponse], error)
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
}

// NewDirectoryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDirectoryServiceHandler(svc DirectoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	directoryServiceMethods := v1.File_seishin_v1_directory_proto.Services().ByName("DirectoryService").Methods()
	directoryServiceListSpacesHandler := connect.NewUnaryHandler(
		DirectoryServiceListSpacesProcedure,
		svc.ListSpaces,
		connect.WithSchema(directoryServiceMethods.ByName("ListSpaces")),
		connect.WithHandlerOptions(opts...),
	)
	directoryServiceGetSpaceHandler := connect.NewUnaryHandler(
		DirectoryServiceGetSpaceProcedure,
		svc.GetSpace,
		connect.WithSchema(directoryServiceMethods.ByName("GetSpace")),
		connect.WithHandlerOptions(opts...),
	)
	directoryServiceListChannelsHandler := connect.NewUnaryHandler(
		DirectoryServiceListChannelsProcedure,
		svc.ListChannels,
		connect.WithSchema(directoryServiceMethods.ByName("ListChannels")),
		connect.WithHandlerOptions(opts...),
	)
	directoryServiceCreateChannelHandler := connect.NewUnaryHandler(
		DirectoryServiceCreateChannelProcedure,
		svc.CreateChannel,
		connect.WithSchema(directoryServiceMethods.ByName("CreateChannel")),
		connect.WithHandlerOptions(opts...),
	)
	directoryServiceListMembersHandler := connect.NewUnaryHandler(
		DirectoryServiceListMembersProcedure,
		svc.ListMembers,
		connect.WithSchema(directoryServiceMethods.ByName("ListMembers")),
		connect.WithHandlerOptions(opts...),
	)
	directoryServiceListRolesHandler := connect.NewUnaryHandler(
		DirectoryServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(directoryServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/seishin.v1.DirectoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DirectoryServiceListSpacesProcedure:
			directoryServiceListSpacesHandler.ServeHTTP(w, r)
		case DirectoryServiceGetSpaceProcedure:
			directoryServiceGetSpaceHandler.ServeHTTP(w, r)
		case DirectoryServiceListChannelsProcedure:
			directoryServiceListChannelsHandler.ServeHTTP(w, r)
		case DirectoryServiceCreateChannelProcedure:
			directoryServiceCreateChannelHandler.ServeHTTP(w, r)
		case DirectoryServiceListMembersProcedure:
			directoryServiceListMembersHandler.ServeHTTP(w, r)
		case DirectoryServiceListRolesProcedure:
			directoryServiceListRolesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDirectoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDirectoryServiceHandler struct{}

func (UnimplementedDirectoryServiceHandler) ListSpaces(context.Context, *connect.Request[v1.ListSpacesRequest]) (*connect.Response[v1.ListSpacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.DirectoryService.ListSpaces is not implemented"))
}

func (UnimplementedDirectoryServiceHandler) GetSpace(context.Context, *connect.Request[v1.GetSpaceRequest]) (*connect.Response[v1.GetSpaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.DirectoryService.GetSpace is not implemented"))
}

func (UnimplementedDirectoryServiceHandler) ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.DirectoryService.ListChannels is not implemented"))
}

func (UnimplementedDirectoryServiceHandler) CreateChannel(context.Context, *connect.Request[v1.CreateChannelRequest]) (*connect.Response[v1.CreateChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.DirectoryService.CreateChannel is not implemented"))
}

func (UnimplementedDirectoryServiceHandler) ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.DirectoryService.ListMembers is not implemented"))
}

func (UnimplementedDirectoryServiceHandler) ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.DirectoryService.ListRoles is not implemented"))
}
