// Ephemeral presence: held in NATS JetStream KV + memory, never Postgres.
// A server restart is expected to reset presence with no correctness impact
// beyond a brief gap. See docs/architecture.md section 5.2.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: seishin/v1/presence.proto

package seishinv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/seishinapp/seishin/api/proto/seishin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PresenceServiceName is the fully-qualified name of the PresenceService service.
	PresenceServiceName = "seishin.v1.PresenceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PresenceServiceSetPresenceProcedure is the fully-qualified name of the PresenceService's
	// SetPresence RPC.
	PresenceServiceSetPresenceProcedure = "/seishin.v1.PresenceService/SetPresence"
	// PresenceServiceListPresenceProcedure is the fully-qualified name of the PresenceService's
	// ListPresence RPC.
	PresenceServiceListPresenceProcedure = "/seishin.v1.PresenceService/ListPresence"
)

// PresenceServiceClient is a client for the seishin.v1.PresenceService service.
type PresenceServiceClient interface {
	SetPresence(context.Context, *connect.Request[v1.SetPresenceRequest]) (*connect.Response[v1.SetPresenceResponse], error)
	ListPresence(context.Context, *connect.Request[v1.ListPresenceRequest]) (*connect.Response[v1.ListPresenceResponse], error)
}

// NewPresenceServiceClient constructs a client for the seishin.v1.PresenceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPresenceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PresenceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	presenceServiceMethods := v1.File_seishin_v1_presence_proto.Services().ByName("PresenceService").Methods()
	return &presenceServiceClient{
		setPresence: connect.NewClient[v1.SetPresenceRequest, v1.SetPresenceResponse](
			httpClient,
			baseURL+PresenceServiceSetPresenceProcedure,
			connect.WithSchema(presenceServiceMethods.ByName("SetPresence")),
			connect.WithClientOptions(opts...),
		),
		listPresence: connect.NewClient[v1.ListPresenceRequest, v1.ListPresenceResponse](
			httpClient,
			baseURL+PresenceServiceListPresenceProcedure,
			connect.WithSchema(presenceServiceMethods.ByName("ListPresence")),
			connect.WithClientOptions(opts...),
		),
	}
}

// presenceServiceClient implements PresenceServiceClient.
type presenceServiceClient struct {
	setPresence  *connect.Client[v1.SetPresenceRequest, v1.SetPresenceResponse]
	listPresence *connect.Client[v1.ListPresenceRequest, v1.ListPresenceResponse]
}

// SetPresence calls seishin.v1.PresenceService.SetPresence.
func (c *presenceServiceClient) SetPresence(ctx context.Context, req *connect.Request[v1.SetPresenceRequest]) (*connect.Response[v1.SetPresenceResponse], error) {
	return c.setPresence.CallUnary(ctx, req)
}

// ListPresence calls seishin.v1.PresenceService.ListPresence.
func (c *presenceServiceClient) ListPresence(ctx context.Context, req *connect.Request[v1.ListPresenceRequest]) (*connect.Response[v1.ListPresenceResponse], error) {
	return c.listPresence.CallUnary(ctx, req)
}

// PresenceServiceHandler is an implementation of the seishin.v1.PresenceService service.
type PresenceServiceHandler interface {
	SetPresence(context.Context, *connect.Request[v1.SetPresenceRequest]) (*connect.Response[v1.SetPresenceResponse], error)
	ListPresence(context.Context, *connect.Request[v1.ListPresenceRequest]) (*connect.Response[v1.ListPresenceResponse], error)
}

// NewPresenceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPresenceServiceHandler(svc PresenceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	presenceServiceMethods := v1.File_seishin_v1_presence_proto.Services().ByName("PresenceService").Methods()
	presenceServiceSetPresenceHandler := connect.NewUnaryHandler(
		PresenceServiceSetPresenceProcedure,
		svc.SetPresence,
		connect.WithSchema(presenceServiceMethods.ByName("SetPresence")),
		connect.WithHandlerOptions(opts...),
	)
	presenceServiceListPresenceHandler := connect.NewUnaryHandler(
		PresenceServiceListPresenceProcedure,
		svc.ListPresence,
		connect.WithSchema(presenceServiceMethods.ByName("ListPresence")),
		connect.WithHandlerOptions(opts...),
	)
	return "/seishin.v1.PresenceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PresenceServiceSetPresenceProcedure:
			presenceServiceSetPresenceHandler.ServeHTTP(w, r)
		case PresenceServiceListPresenceProcedure:
			presenceServiceListPresenceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPresenceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPresenceServiceHandler struct{}

func (UnimplementedPresenceServiceHandler) SetPresence(context.Context, *connect.Request[v1.SetPresenceRequest]) (*connect.Response[v1.SetPresenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.PresenceService.SetPresence is not implemented"))
}

func (UnimplementedPresenceServiceHandler) ListPresence(context.Context, *connect.Request[v1.ListPresenceRequest]) (*connect.Response[v1.ListPresenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.PresenceService.ListPresence is not implemented"))
}
