// Identity and session establishment: the handshake described in
// docs/protocol.md section 3, expressed as Canonical Platform API messages.
// The native protocol adds framing on top of these same messages; it defines
// no session semantics of its own.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: seishin/v1/session.proto

package seishinv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/seishinapp/seishin/api/proto/seishin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "seishin.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceHelloProcedure is the fully-qualified name of the SessionService's Hello RPC.
	SessionServiceHelloProcedure = "/seishin.v1.SessionService/Hello"
	// SessionServiceAuthenticateProcedure is the fully-qualified name of the SessionService's
	// Authenticate RPC.
	SessionServiceAuthenticateProcedure = "/seishin.v1.SessionService/Authenticate"
	// SessionServiceResumeProcedure is the fully-qualified name of the SessionService's Resume RPC.
	SessionServiceResumeProcedure = "/seishin.v1.SessionService/Resume"
)

// SessionServiceClient is a client for the seishin.v1.SessionService service.
type SessionServiceClient interface {
	Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error)
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error)
}

// NewSessionServiceClient constructs a client for the seishin.v1.SessionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := v1.File_seishin_v1_session_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		hello: connect.NewClient[v1.HelloRequest, v1.HelloResponse](
			httpClient,
			baseURL+SessionServiceHelloProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Hello")),
			connect.WithClientOptions(opts...),
		),
		authenticate: connect.NewClient[v1.AuthenticateRequest, v1.AuthenticateResponse](
			httpClient,
			baseURL+SessionServiceAuthenticateProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Authenticate")),
			connect.WithClientOptions(opts...),
		),
		resume: connect.NewClient[v1.ResumeRequest, v1.ResumeResponse](
			httpClient,
			baseURL+SessionServiceResumeProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Resume")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	hello        *connect.Client[v1.HelloRequest, v1.HelloResponse]
	authenticate *connect.Client[v1.AuthenticateRequest, v1.AuthenticateResponse]
	resume       *connect.Client[v1.ResumeRequest, v1.ResumeResponse]
}

// Hello calls seishin.v1.SessionService.Hello.
func (c *sessionServiceClient) Hello(ctx context.Context, req *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// Authenticate calls seishin.v1.SessionService.Authenticate.
func (c *sessionServiceClient) Authenticate(ctx context.Context, req *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return c.authenticate.CallUnary(ctx, req)
}

// Resume calls seishin.v1.SessionService.Resume.
func (c *sessionServiceClient) Resume(ctx context.Context, req *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error) {
	return c.resume.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the seishin.v1.SessionService service.
type SessionServiceHandler interface {
	Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error)
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := v1.File_seishin_v1_session_proto.Services().ByName("SessionService").Methods()
	sessionServiceHelloHandler := connect.NewUnaryHandler(
		SessionServiceHelloProcedure,
		svc.Hello,
		connect.WithSchema(sessionServiceMethods.ByName("Hello")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceAuthenticateHandler := connect.NewUnaryHandler(
		SessionServiceAuthenticateProcedure,
		svc.Authenticate,
		connect.WithSchema(sessionServiceMethods.ByName("Authenticate")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceResumeHandler := connect.NewUnaryHandler(
		SessionServiceResumeProcedure,
		svc.Resume,
		connect.WithSchema(sessionServiceMethods.ByName("Resume")),
		connect.WithHandlerOptions(opts...),
	)
	return "/seishin.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceHelloProcedure:
			sessionServiceHelloHandler.ServeHTTP(w, r)
		case SessionServiceAuthenticateProcedure:
			sessionServiceAuthenticateHandler.ServeHTTP(w, r)
		case SessionServiceResumeProcedure:
			sessionServiceResumeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.SessionService.Hello is not implemented"))
}

func (UnimplementedSessionServiceHandler) Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.SessionService.Authenticate is not implemented"))
}

func (UnimplementedSessionServiceHandler) Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("seishin.v1.SessionService.Resume is not implemented"))
}
